[package]
name = "chip8_interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sfmx = { path = "../sfmx" }
rand = "*"
rfd = "0.11.2"
rodio = "0.17.1"
